name: ci-teste-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node main.js